module.exports = {
  pickerBoyDetailsFetchedSuccessfully: 'PickerBoy Details Fetched Successfully',
  pickerBoyDetailsNotFound: 'PickerBoy Details Not Found !',
  pickerBoyIdInvalidEitherDeletedOrDeactivated: 'Picker Boy Id is Invalid or is either deleted !',
  invalidPickerBoy: 'The Picker Boy id is Invalid !',
  pickerBoyListFetchedSuccessfully: 'Picker Boy List Fetched Successfully !',

  zohoServerError: 'Zoho Server Error, Data Not Found!.',
  userDetailsFetched: 'User Details Fetched Successfully from Zoho !.',
  asmCreated: 'Area Sales Manager Created Successfully !',
  asmNotCreated: 'Unable to Create Area Sales Manager !',
  asmAlreadyCreated: 'Area Sales Manager already created !',
  invalidAsmId: 'The ASM id is Invalid !',
  asmIdInvalidEitherDeletedOrDeactivated: 'ASM Id is either deleted or deactivated !',
  dataIsNotChanged: 'Following Data is Not Changed - ',
  asmUpdatedSuccessfully: 'ASM Updated Successfully !',
  asmNotUpdated: 'Error! Updating ASM !',
  asmDetailsFetchedSuccessfully: 'Asm Details Fetched Successfully !',
  asmDetailsNotFound: 'Asm Details Not Fetched !',
  asmAlreadyActivated: 'Asm Already Activated !',
  asmAlreadyDeactivated: 'Asm Already Deactivated !',
  asmDeletedSuccessfully: 'Asm Deleted Successfully !',
  asmNotDeletedSuccessfully: 'Asm Not Deleted!',
  asmDeactivatedSuccessfully: 'Asm Deactivated Successfully !',
  asmActivatedSuccessfully: 'Asm Activated Successfully !',
  salesmanAleadyCreated: 'Salesman Already Created !',
  asmIdIsInvalidOrDeactivatedForSalesman: 'Reporting Manager is not registered or not valid !',
  salesmanCreated: 'Salesman Successfully Created !',
  salesmanNotCreated: 'Salesman Not Created Successfully !',
  salesmanDetailsFetchedSuccessfully: 'Salesman Details Fetched Successfully',
  salesmanDetailsNotFound: 'Salesman Details Not Found !',
  salesmanAlreadyActivated: 'Salesman Already Activated !',
  salesmanAlreadyDeactivated: 'Salesman Already Deactivated !',
  invalidSalesmanId: 'The Salesman id is Invalid !',
  salesmanDeactivatedSuccessfully: 'Salesman Deactivated Successfully !',
  salesmanActivatedSuccessfully: 'Salesman Activated Successfully !',
  salesmanNotUpdated: 'Salesman Not Updated !',
  salesmanDeletedSuccessfully: 'Salesman Deleted Successfully !',
  salesmanNotDeletedSuccessfully: 'Salesman Not Deleted !',
  salesmanUpdatedSuccessfully: 'Salesman Updated Successfully!',
  salesmanNotUpdatedSuccessfully: 'Salesman Not Updated!',
  salesmanImapactSuccessful: 'Salesman Getting Effected Fetched Successful!',
  salesmanImapactNotSuccessful: 'Salesman Getting Effected Not Fetched!',
  employeeCreated : "Employee Successfully Created !",
  employeeNotCreated :"Employee Not Created Successfully !",
  deliveryExecutiveCreated :"Delivery Executive Successfully Created !",
  deliveryExecutiveNotCreated : "Delivery Executive Not Created Successfully !",
  deliveryExecutiveFetchedSuccessfully : "Delivery Executive Fetched Successfully !",
  deliveryExecutiveNotFound :"Delivery Executive Not Fetched !",
  deliveryExecutiveDeletedSuccessfully:"Delivery Executive Successfully !",
  deliveryExecutiveNotDeletedSuccessfully: "Delivery Executive Deleted!",
  deliveryExecutiveUpdatedSuccessfully : "Delivery Executive Updated Successfully!",
  deliveryExecutiveNotUpdatedSuccessfully : "Delivery Executive Not Updated !",
  deliveryExecutiveActivatedSuccessfully : "Delivery Executive Activated Successfully !",
  deliveryExecutiveDeactivatedSuccessfully : "Delivery Executive Deactivated Successfully !",
  securityGuardCreated: "Security Guard Successfully Created !",
  securityGuardNotCreated : "Security Guard Not Created Successfully !",
  securityGuardFetchedSuccessfully : "Security Guard Fetched Successfully !",
  securityGuardNotFound :"Security Guard Not Fetched !",
  securityGuardDeletedSuccessfully:"Security Guard Deleted Successfully !",
  securityGuardeNotDeletedSuccessfully: "Security Guard Not Deleted !",
  securityGuardUpdatedSuccessfully : "Security Guard Updated Successfully !",
  securityGuardNotUpdatedSuccessfully : "Security Guard Not Updated !",
  securityguardActivatedSuccessfully : "Security Guard Activated Successfully !",
  securityguardDeactivatedSuccessfully : "Security Guard Deactivated Successfully !",
  pickerBoyCreated : "Picker Boy Created Successfully !",
  pickerBoyNotCreated : "Picker Boy Not Created Successfully !",
  pickerBoyDeletedSuccessfully : "Picker Boy Deleted Successfully !",
  pickerBoyNotDeletedSuccessfully : "Picker Boy Not Deleted !",
  pickerboyActivatedSuccessfully : "Pickerboy Activated Successfully !",
  pickerboyDeactivatedSuccessfully : "Pickerboy Deactivated Successfully !",
  pickerboyNotUpdated : "pickerboy Not Updated Successfully !",
  invalidSalesmanIds: (salesmanIds) => {
    return `Invalid Salesman Id Found ${salesmanIds}`
  },
  salesmanIdInvalidEitherDeletedOrDeactivated: 'Salesman Id is Invalid or is either deleted !',
  sameEmpIsAlreadyCreatedAsAsm: 'Same Employee is already Created as ASM !',
  sameUserIsAlreadyASalesman: 'Same Employee is already Created as Salesman !',
  onboardedCustomersList: 'Onboarded Customer List Fetched Successfully !',
  salesmanListFetchedSuccessfully: 'Salesman List Fetched Successfully !',
  asmFetchedSuccessfully: 'ASM listed Successfully !',
  unableToDownload: (type) => {
    return `Unable to download ${type} right now, please try again after sometime !`
  }
};