module.exports = {
  pickerBoyDetailsFetchedSuccessfully: 'PickerBoy Details Fetched Successfully',
  pickerBoyDetailsNotFound: 'PickerBoy Details Not Found !',
  pickerBoyIdInvalidEitherDeletedOrDeactivated: 'Picker Boy Id is Invalid or is either deleted !',
  invalidPickerBoy: 'The Picker Boy id is Invalid !',
  pickerBoyListFetchedSuccessfully: 'Picker Boy List Fetched Successfully !',
  pickerBoyCreated: "Picker Boy Successfully Created !",
  pickerBoyNotCreated: "Unable to create Picker Boy !",

  zohoServerError: 'Zoho Server Error, Data Not Found!.',
  userDetailsFetched: 'User Details Fetched Successfully from Zoho !.',
  userDetailsNotFetched: 'Unable to fetched the User Details from Zoho !.',
  dataIsNotChanged: 'Following Data is Not Changed - ',
  employeeCreated: "Employee Successfully Created !",
  employeeNotCreated: "Employee Not Created Successfully !",
  deliveryExecutiveCreated: "Delivery Executive Successfully Created !",
  deliveryExecutiveNotCreated: "Unable to create Delivery Executive !",
  deliveryExecutiveFetchedSuccessfully: "Delivery Executive Fetched Successfully !",
  deliveryExecutiveNotFound: "Delivery Executive Not Fetched !",
  deliveryExecutiveDeletedSuccessfully: "Delivery Executive Successfully !",
  deliveryExecutiveNotDeletedSuccessfully: "Delivery Executive Deleted!",
  deliveryExecutiveUpdatedSuccessfully: "Delivery Executive Updated Successfully!",
  deliveryExecutiveNotUpdatedSuccessfully: "Delivery Executive Not Updated !",
  deliveryExecutiveNotUpdatedSuccessfully: "Delivery Executive Not Updated !",
  deliveryExecutiveActivatedSuccessfully: "Delivery Executive Activated Successfully !",
  deliveryExecutiveDeactivatedSuccessfully: "Delivery Executive Deactivated Successfully !",
  securityGuardCreated: "Security Guard Successfully Created !",
  securityGuardNotCreated: "Unable to create Security Guard !",
  securityGuardFetchedSuccessfully: "Security Guard Fetched Successfully !",
  securityGuardNotFound: "Security Guard Not Fetched !",
  securityGuardDeletedSuccessfully: "Security Guard Deleted Successfully !",
  securityGuardeNotDeletedSuccessfully: "Security Guard Not Deleted!",
  pickerboyActivatedSuccessfully: "Pickerboy Activated Successfully !",
  pickerboyDeactivatedSuccessfully: "Pickerboy Deactivated Successfully !",
  pickerboyNotUpdated: "pickerboy Not Updated Successfully !",
  onboardedCustomersList: 'Onboarded Customer List Fetched Successfully !',
  deliveryExecutiveUpdatedSuccessfully: 'Delivery Executive Updated Successfully !',
  deliveryExecutiveNotUpdated: 'Error! Updating Delivery Executive!',
  securityGuardUpdatedSuccessfully: 'Security Guard Updated Successfully !',
  securityGuardNotUpdated: 'Error! Updating Security Guard!',
  pickerBoyUpdatedSuccessfully: 'Picker Boy Updated Successfully !',
  pickerBoyNotUpdated: 'Error! Updating Picker Boy!',
};