module.exports = {
    grnCreated: 'Grn generated Successfully !',
    grnAlreadyGenerated: 'Grn already generated !',
    grnNotGenerated: 'Grn not generated !',
    invoicesDetailsFetched: 'invoice Details Fetched Successfully !.',
    invoicesDetailsNotFound: 'invoice Details Not Fetched !',
    invoicesMappingNotFound: 'invoice mapping Not Fetched !',
    salesOrderNotFound: 'salesOrder Not Fetched !',
    poListFetched: 'Purchase order fetched Successfully !',
    purchaseOrderIdInvalidEitherDeletedOrDeactivated: 'Purchase Order Id is either deleted or deactivated !',
    purchaseOrderReceivingIdEitherDeletedOrDeactivated: 'Purchase Order Receiving Id is either deleted or deactivated !',
    invalidPurchaseOrderId: 'The Purchase Order id is Invalid !',
    purchaseOrderAlreadyAddedInReceivingState: 'Purchase Order  Already Added in Receiving State!',
    invalidPickerBoyPurchaseOrderMappingId: 'The Picker Boy Purchase Order Mapping Id is Invalid !',
    receivePOItem:"Received Purchase Order Item added successfully",
    startedReceiving:"Picker boy started receiving for purchase order",
    startedNotReceiving:"Error in starting receiving itemsfor purchase order",
    poDetailsFetched:"Purchase order details fetched successfully",
    purchaseOrderGRNalreadygenerated: 'GRN already generated for this Purchase Order.',
    emptyBucketList: 'Bucket list is empty',
    bucketListFetchedSuccessfully: 'Bucket List is fetched Successfully',
    invalidPurchaseOrderId:"Invalid Purchase Order Id",
    invalidPurchaseOrderGRNId:"Invalid Purchase Order GRN Id",
    receivedQuantityGreaterThanQty:"Received quantity cant be greater than quantity to be received",
    invalidPurchaseOrderReceivingId:"Invalid Purchase Order Receiving Id",
    grnGeneratedSuccessfully:"GRN generated Successfully",
    grnRecordNotExist:"GRN record does not exsist",
    receiverBoyIdInvalid:"Receiver Boy Id is Invalid",
    itemNotFound:"Item not found for this purchase order",
    invalidItemId:"Invalid Item Id",
    requiredRemark:"Remarks is required as entered quantity is not equal to quantity to be received",
    alreadyHasOngoinOrder:"you already Have one Ongoing receiving Order.Please generate grn for that first.",

};