module.exports = {

    roleCreated: 'Role Created Successfully !',
    roleNotCreated: 'Unable to Create Role !',
    rolesDetailsFetched: 'Roles Details Fetched Successfully !.',
    rolesDetailsNotFound: 'Roles Details Not Fetched !',
    roleUpdatedSuccessfully: 'Role Updated Successfully !',
    roleNotUpdated: 'Error! Updating Role !',
    roleDeletedSuccessfully: 'Role Deleted Successfully !',
    roleNotDeletedSuccessfully: 'Role Not Deleted!',

    zohoServerError: 'Zoho Server Error, Data Not Found!.',

    userDetailsFetched: 'User Details Fetched Successfully from Zoho !.',

    asmAlreadyCreated: 'Area Sales Manager already created !',
    invalidAsmId: 'The ASM id is Invalid !',
    asmIdInvalidEitherDeletedOrDeactivated: 'ASM Id is either deleted or deactivated !',
    dataIsNotChanged: 'Following Data is Not Changed - ',
    asmUpdatedSuccessfully: 'ASM Updated Successfully !',
    asmNotUpdated: 'Error! Updating ASM !',
    asmDetailsFetchedSuccessfully: 'Asm Details Fetched Successfully !',
    asmDetailsNotFound: 'Asm Details Not Fetched !',
    asmAlreadyActivated: 'Asm Already Activated !',
    asmAlreadyDeactivated: 'Asm Already Deactivated !',
    asmDeletedSuccessfully: 'Asm Deleted Successfully !',
    asmNotDeletedSuccessfully: 'Asm Not Deleted!',
    asmDeactivatedSuccessfully: 'Asm Deactivated Successfully !',
    asmActivatedSuccessfully: 'Asm Activated Successfully !',
    salesmanAleadyCreated: 'Salesman Already Created !',
    asmIdIsInvalidOrDeactivatedForSalesman: 'Reporting Manager is not registered or not valid !',
    salesmanCreated: 'Salesman Successfully Created !',
    salesmanNotCreated: 'Salesman Not Created Successfully !',
    salesmanDetailsFetchedSuccessfully: 'Salesman Details Fetched Successfully',
    salesmanDetailsNotFound: 'Salesman Details Not Found !',
    salesmanAlreadyActivated: 'Salesman Already Activated !',
    salesmanAlreadyDeactivated: 'Salesman Already Deactivated !',
    invalidSalesmanId: 'The Salesman id is Invalid !',
    salesmanDeactivatedSuccessfully: 'Salesman Deactivated Successfully !',
    salesmanActivatedSuccessfully: 'Salesman Activated Successfully !',
    salesmanNotUpdated: 'Salesman Not Updated !',
    salesmanDeletedSuccessfully: 'Salesman Deleted Successfully !',
    salesmanNotDeletedSuccessfully: 'Salesman Not Deleted !',
    salesmanUpdatedSuccessfully: 'Salesman Updated Successfully!',
    salesmanNotUpdatedSuccessfully: 'Salesman Not Updated!',
    salesmanImapactSuccessful: 'Salesman Getting Effected Fetched Successful!',
    salesmanImapactNotSuccessful: 'Salesman Getting Effected Not Fetched!',
    invalidSalesmanIds: (salesmanIds) => {
        return `Invalid Salesman Id Found ${salesmanIds}`
    },
    salesmanIdInvalidEitherDeletedOrDeactivated: 'Salesman Id is Invalid or is either deleted !',
};