module.exports = {
    goFrugalConfigNotFound: 'Go Frugal Configuration Not Found !',
    goFrugalServerError: 'Go Frugal Server Error! Please try after sometime !',
    salesOrderInsertInitiated: 'SalesOrder Sync Initiated, Please check after 10 mins !',
    toDoSalesOrderDetailsFetchedSuccessfully: 'To Do Sales Order Details Fetched Successfully !',
    unableToFetchToDoSalesOrderDetails: 'To Do SalesOrder Details not Fetched !',
    salesOrderNotFound: 'To Do SalesOrder Details Not Found !',
    salesOrderDetailsFetched: 'SalesOrder Details Fetched Successfully !.',
    salesOrderDetailsNotFetched: 'SalesOrder Details not Fetched !.',
    salesOrderIdInvalidEitherDeletedOrDeactivated: 'sales Order Id is either deleted or deactivated !',
    invalidSalesOrderId: 'The Sales Order id is Invalid !',
    salesOrderNotAddedInPackingStage: 'Unable to add Sales Order in packing step !',
    salesOrderAddedInPackingStage: ' Sales Order added in packing step Successfully !',
    itemAddedInsalesOrderAfterScan: 'Item added in SalesOrder Details after scan Successfully !.',
    unableToAddItemInsalesOrderAfterScan: 'Unable to add Item  in SalesOrder Details after scan !.',
    customerDetailsFetchedSuccessfully: 'Customer Details Fetched Successfully !',
    unableToFetchedCustomerDetails: 'Unable to fetch Customer Details!',
    itemAlreadyAdded: 'Item Already Added after Scan!',
    itemDataIsNotChanged: 'Item Details are not changed!',
    itemUpdatedSuccessfully: 'Item Updated Successfully !',
    itemNotUpdated: 'Error! Updating Item !',
    //picker sales order mapping id
    salesOrderAlreadyAddedInPickerState: 'Sales Order  Already Added in Picker State!',
    invalidPickerBoySalesOrderMappingId: 'The Picker Boy Sales Order Mapping Id is Invalid !',
    pickerBoySalesOrderIdInvalidEitherDeletedOrDeactivated: 'Picker Boy Sales Order Id is either deleted or deactivated !',

};