module.exports = {
    goFrugalConfigNotFound: 'Go Frugal Configuration Not Found !',
    goFrugalServerError: 'Go Frugal Server Error! Please try after sometime !',
    salesOrderInsertInitiated: 'SalesOrder Sync Initiated, Please check after 10 mins !',
    toDoSalesOrderDetailsFetchedSuccessfully: 'To Do Sales Order Details Fetched Successfully !',
    unableToFetchToDoSalesOrderDetails: 'To Do SalesOrder Details not Fetched !',
    salesOrderNotFound: 'To Do SalesOrder Details Not Found !',
    salesOrderDetailsFetched: 'SalesOrder Details Fetched Successfully !.',
    salesOrderDetailsNotFetched: 'SalesOrder Details not Fetched !.',
    salesOrderIdInvalidEitherDeletedOrDeactivated: 'sales Order Id is either deleted or deactivated !',
    invalidSalesOrderId: 'The Sales Order id is Invalid !',
    invalidPickerBoySalesOrderId: 'The Picker Boy Sales Order id is Invalid !',
    salesOrderNotAddedInPackingStage: 'Unable to add Sales Order in packing step !',
    salesOrderAddedInPackingStage: ' Sales Order added in packing step Successfully !',
    itemAddedInsalesOrderAfterScan: 'Item added in SalesOrder Details after scan Successfully !.',
    bucketItemListFetchSuccesfully: 'Bucket item Details fetched Successfully !.',
    InvoiceGeneratedSuccesfully: 'Invoice Generated Successfully !.',
    InvoiceUpdateFailed: 'Invoice Update Failed !.',
    unableToAddItemInsalesOrderAfterScan: 'Unable to add Item  in SalesOrder Details after scan !.',
    unableToFetchBucketItemList: 'Unable To Fetch Bucket Details !.',
    customerDetailsFetchedSuccessfully: 'Customer Details Fetched Successfully !',
    unableToFetchedCustomerDetails: 'Unable to fetch Customer Details!',
    itemAlreadyAdded: 'Item Already Added after Scan!',
    itemDataIsNotChanged: 'Item Details are not changed!',
    itemUpdatedSuccessfully: 'Item Updated Successfully !',
    itemNotUpdated: 'Error! Updating Item !',
    //picker sales order mapping id
    salesOrderAlreadyAddedInPickerState: 'Sales Order  Already Added in Picker State!',
    invalidPickerBoySalesOrderMappingId: 'The Picker Boy Sales Order Mapping Id is Invalid !',
    pickerBoySalesOrderIdInvalidEitherDeletedOrDeactivated: 'Picker Boy Sales Order Id is either deleted or deactivated !',
    pickerBoyDetailsUpdated: 'PickerBoy Details Updated Successfully  !',
    pickerBoyDetailsNotUpdated: 'Error! Updating PickerBoy details !',
    pickerBoyAlreadyInPickingState:'Already in picking State',
    // pending sales order details
    pendingSalesOrderFetchedSuccessfully: 'Pending SalesOrder Details Fetched Successfully !',
    todoOrderFetchedSuccessfully: 'Todo Order Details Fetched Successfully !',
    unableToFetchedPendingSalesOrder: 'Unable to fetch Pending SalesOrder Details!',
    //pickerboy salesorder mapping id or item code is invalid
    pickerBoySalesOrderIdOrItemCodeInvalidEitherDeletedOrDeactivated: 'Picker Boy Sales Order Id or Item Code is either deleted or deactivated !',
    pickerBoySalesOrderInvoiceGeneratedSuccesfully:'SalesOrder Invoice Generated Succesfully!',
    pickerBoySalesOrderInvoiceGeneratedFailed:'Failed To generate SalesOrder Invoice!',
    pickerBoySalesOrdereDeliverySuccesfully:'Succesfully Generated Sales Order Delivery Number!',
    pickerBoySalesOrdereDeliveryNumberFailed:'Failed To Generate Sales Order Delivery Number!',
    pickerBoySalesOrderInvoiceGeneratedAndUpdatedSuccesfully:'SalesOrder Invoice Generated And Updated Succesfully!',
    pickerBoySalesOrderInvoiceUploadFailed:'Failed To Upload SalesOrder Invoice!',
    pickerBoySalesOrdereDeliveryAndUpdatedSuccesfully:'Succesfully Generated Sales Order Delivery Number And Updated!',
    pickerBoySalesOrdereDeliveryNumberUploadFailed:'Failed To Upload Sales Order Delivery Number!',
    pickerBoySalesOrderDeliveryNumberAlreadyGenerated: "This item already being updated.",
    pickerBoySalesOrderFetchingInvoiceFailed:"Error Fetching Invoice!"


};