module.exports = {
  attendanceMarkedSuccessfully: "Vehicle Checked In !",
  attendanceNotMarkedSuccessfully:
    "Attendance Not Marked Successfully, Please try again after sometime !",
  vehicleCheckedOut: "Vehicle Checked Out Successfully !",
  vehicleCheckedNotOut: "Server Error! Please try after sometime !",
  tripListFetched: "Trip List Fetched Successfully !",
  tripListNotFetched: "Trip List not Fetched !",
  vehicleNotFetched: "Vehicle Details Not Fetched !",
  vehicleIdInvalidEitherDeletedOrDeactivated:
    "Vehicle Id is either deleted or deactivated !",
  invalidVehicleId: "The Vehicle id is Invalid !",
  tripDetailsFetched: "Trip Details Fetched Successfully !",
  tripDetailsNotFetched: "Trip Details not Fetched !",
  gpnDetailsFetched: "GPN Details Fetched Successfully !",
  gpnDetailsNotFetched: "GPN Details not Fetched !",
  gpnVerified: "GPN verified Successfully",
  gpnNotVerified: "GPN Not Verified",
  tripHistoryListFetched: "Trip History List Fetched Successfully.",
  tripHistoryListNotFetched: "Trip History List Not Fetched.",
  cratesUpdated: "crates Updated Successfully",
  invoiceVerified: "Invoice Verified Successfully",
  invoiceNotVerified: "Invoice Not Verified",
  itemsIdsFetched: "Item Ids List Fetched Successfully",
  itemsIdsNotFetched: "Item Ids List Not Fetched",
  vehicleAllowed: "Vehicle Allowed Successfully",
  vehicleNotAllowed: "Vehicel not Allowed",
  gpnIsValid:"GPN is Valid",
  gpnIsInvalid:"GPN format is Invalid",
  gpnDataTypeIsInvalid:"GPN data type is Invalid",
  invoiceExists:"Invoice exists",
  invoiceDoesNotExists: "Couldn't find invoice'",
  invoiceNoDataTypeIsInvalid:"Invoice number data type is Invalid",
  invoiceAlreadyVerified:"This invoice is already verified",
  disputeDetailsUpdated: "Dispute Details Updated Successfully",
  disputeDetailsNotUpdated: "Unable to update Dispute Details",


};
