module.exports = {
    grnCreated: 'STI generated Successfully !',
    grnAlreadyGenerated: 'STI already generated !',
    grnNotGenerated: 'STI not generated !',
    grnNotGeneratedinSAP: 'Error in generating STI into the system',
    stiListFetched: 'Stock Transfer Rrecord fetched Successfully !',
    stiIdInvalidEitherDeletedOrDeactivated: 'Stock Transfer Record Id is either deleted or deactivated !',
    stiReceivingIdEitherDeletedOrDeactivated: 'Stock Transfer Record Receiving Id is either deleted or deactivated !',
    invalidStockTransferId: 'The Stock Transfer Record id is Invalid !',
    stiAlreadyAddedInReceivingState: 'Stock Transfer Record  Already Added in Receiving State!',
    invalidPickerBoyStockTransferMappingId: 'The Picker Boy Stock Transfer Record Mapping Id is Invalid !',
    receiveSTIItem:"Received Stock Transfer Record Item added successfully",
    startedReceiving:"Picker boy started receiving for purchase order",
    startedNotReceiving:"Error in starting receiving itemsfor purchase order",
    stiDetailsFetched:"Stock Transfer Rrecord details fetched successfully",
    stiGRNalreadygenerated: 'STI already generated for this Stock Transfer Record.',
    emptyBucketList: 'Bucket list is empty',
    bucketListFetchedSuccessfully: 'Bucket List is fetched Successfully',
    invalidStockTransferId:"Invalid Stock Transfer Record Id",
    invalidStockTransferGRNId:"Invalid Stock Transfer Record STI Id",
    receivedQuantityGreaterThanQty:"Received quantity cant be greater than quantity to be received",
    invalidStockTransferReceivingId:"Invalid Stock Transfer Record Receiving Id",
    grnGeneratedSuccessfully:"STI generated Successfully",
    grnRecordNotExist:"STI record does not exsist",
    receiverBoyIdInvalid:"Receiver Boy Id is Invalid",
    receiverItemIdInvalid:"Receiver Item Id is Invalid",
    itemNotFound:"Item not found for this purchase order",
    invalidItemId:"Invalid Item Id",
    upcomingDeliverDateMissing:"Upcoming Delivery Date is Missing",
    partialFlowNotAllowed:"Partial Flow Not Allowed ",
    pastDateNotAllowedforUDD:"For Upcoming Deliver Date past date is not allowed",
    requiredRemark:"Remarks is required as entered quantity is not equal to quantity to be received",
    alreadyHasOngoinOrder:"you already Have one Ongoing receiving Order.Please generate STI for that first.",
    errorInGettingVendorDetails:"Error in getting vendor details",
    vendorDetailsNotFound:"Vendor Details not Found",
    stiDetailsNotFound:"Stock Transfer Rrecord details not found",

};