module.exports = {
    transporterMasterCreated: 'Transporter Master Successfully Created !',
    transporterMasterNotCreated: 'Transporter Master Not Created Successfully !',
    transporterMasterFetched :'Transporter Master Fetched Successfully !',
    transporterMasterNotFetched :'Transporter Master Not Fetched Successfully !',
    transporterMasterUpdated:'Transporter Master Updated Successfully !',
    transporterMasterNotUpdated:'Transporter Master Not Updated Successfully !',
    transporterDeleted:'Transporter Master Deleted Successfully !',
    transporterNotDeleted:'Transporter Master Not Deleted Successfully !',
    rateCategoryCreated: 'Rate Category Successfully Created !',
    rateCategoryNotCreated: 'Rate Category Not Created Successfully!',
    rateCategoryFetched : 'Rate Category Fetched Successfully !',
    rateCategoryNotFetched : 'Rate Category Not Fetched Successfully!',
    rateCategoryUpdated: 'Rate Category Updated Successfully !',
    rateCategoryNotUpdatedSuccessfully: 'Rate Category Not Updated Successfully !',
    rateCategoryDeletedSuccessfully: 'Rate Category Deleted Successfully !',
    rateCategoryNotDeletedSuccessfully: 'Rate Category Not Deleted Successfully !',
    newTransporterCreated: 'New Transporter Successfully Created',
    newTransporterNotCreated: 'New Transporter Not Created Successfully',
    newTransporterFetched : 'New Transporter Fetched Successfully !',
    newTransporterNotFetched : 'New Transporter Not Fetched Successfully !',
    newTransporterNotUpdated : 'New Transporter Updated Successfully !',
    newTransporterNotUpdated : 'New Transporter Not Updated Successfully !',
    newTransporterDeleted : 'New Transporter Deleted Successfully !',
    newTransporterNotDeleted : "New Transporter Not Deleted Successfully !",
    vehicleCreated: 'Vehicle Successfully Created',
    vehicleNotCreated: 'Vehicle Not Created Successfully',
    vehicleFetched : 'Vehicle Fetched Successfully !',
    vehicleNotFetched : 'Vehicle Not Fetched Successfully !',
    vehicleNotUpdated : 'Vehicle Updated Successfully !',
    vehicleNotUpdated : 'Vehicle Not Updated Successfully !',
    vehicleDeleted : 'Vehicle Deleted Successfully !',
    vehicleNotDeleted : "Vehicle Not Deleted Successfully !"
}