module.exports = {
    transporterMasterCreated: 'Transporter Master Successfully Created !',
    transporterMasterNotCreated: 'Transporter Master Not Created Successfully !',
    transporterMasterFetched :'Transporter Master Fetched Successfully !',
    transporterMasterNotFetched :'Transporter Master Not Fetched Successfully !',
    transporterMasterUpdated:'Transporter Master Updated Successfully !',
    transporterMasterNotUpdated:'Transporter Master Not Updated Successfully !',
    transporterDeleted:'Transporter Master Deleted Successfully !',
    transporterNotDeleted:'Transporter Master Not Deleted Successfully !',
    rateCategoryCreated: 'Rate Category Successfully Created !',
    rateCategoryNotCreated: 'Rate Category Not Created Successfully!',
    rateCategoryFetched : 'Rate Category Fetched Successfully !',
    rateCategoryNotFetched : 'Rate Category Not Fetched Successfully!',
    rateCategoryUpdated: 'Rate Category Updated Successfully !',
    rateCategoryNotUpdatedSuccessfully: 'Rate Category Not Updated Successfully !',
    rateCategoryDeletedSuccessfully: 'Rate Category Deleted Successfully !',
    rateCategoryNotDeletedSuccessfully: 'Rate Category Not Deleted Successfully !',
    transporterCreated: 'New Transporter Successfully Created',
    transporterNotCreated: 'New Transporter Not Created Successfully',
    transporterFetched : 'New Transporter Fetched Successfully !',
    transporterNotFetched : 'New Transporter Not Fetched Successfully !',
    transporterNotUpdated : 'New Transporter Updated Successfully !',
    transporterNotUpdated : 'New Transporter Not Updated Successfully !',
    transporterDeleted : 'New Transporter Deleted Successfully !',
    transporterNotDeleted : "New Transporter Not Deleted Successfully !",
    transporterRatecategory: 'Transporter Ratecategory Successfully Created ',
    transporterRatecateNotCreated: "Ratecategory Not Successfully Created",
    transporterIdIsInvalidOrDeactivated: 'Transporter Id is Invalid or Deactivated !',
    transporterId: 'Transporter is Invalid !',
    dataIsNotChanged: 'Following Data is Not Changed - ',
    transporterIdInvalidEitherDeletedOrDeactivated: 'transporter Id is either deleted or deactivated !',
}