module.exports = {
  'loginInfoFetched': 'login Info Fetched Successfully',
  'loginInfoNotFetched': 'Unable to Fetch login Info !',
  'attemptExhausted': 'Number of Attempt Exhausted, Please check your email or try after sometime!',
  'userLoggedIn': 'User Logged In Successfully',
  'emailIdNotUnique': 'Email Id or Emp Id is already registered, Please login to continue',
  'passwordMissing': 'Password Field is Missing',
  'userCreatedSuccessfully': 'User Created Successfully',
  'userNotCreated': 'User Not Created!',
  'emailIsNotValid': 'Email is not valid',
  'incorrectPassword': 'Password is Incorrect!',
  'invalidLogin': 'Invalid Login !',
  'validLogin': 'Valid Login !',
  'incorrectEmailId': 'Incorrect Email Id !',
  'forgetPasswordEmailNotSend': 'Error Sending Email, Please try after sometime!',
  'emailSend': 'An Email with instructions is been generated and send to your email id, Please follow to reset your password.',
  'forgetPasswordTokenExpired': 'Token Expired, Please generate a new request to change password !',
  'tokenHampered': 'The token is invalid, and is reported in the server!',
  'tokenIsValid': 'Token is Valid !',
  'updatedPassword': 'Password Updated for the user!',
  'passwordNotUpdated': 'Error Updating the password !',
  'invalidUser': 'User is Invalid!',
  'sameAsOldPassword': 'The New Password is same as the existing password!',
  'authTokenIsRequired': 'x-access-token is required !',
  'invalidToken': 'User Auth Token is invalid !',
  'userDetailsFetched': 'User Details Fetched Successfully',
  'userDetailsNotFetched': 'Unable to Fetch User Details !',
  'tokenExpired': 'Token Expired, Please login again!',
  'cityNotAllocatedToTheAdmin': 'City Not Allocated to the admin user !',
  'emailIdAlreadyExist': 'Email id Already exist - ',
  'userUpdatedSuccessfully': 'User Details Updated Successfully !',
  'userUpdatedNotSuccessfully': 'User Details Not Updated Successfullt !',
  'unauthorizedUser': 'Unauthorized Access !',
  'managerListFetchedSuccessfully': 'Manager List Fetched Successfully !',
  'statusNotChanged': (status) => {
    return `User is already ${status ? 'actived' : 'deactived'}, Please ${status ? 'deactivate' : 'activate'} it first !`;
  },
  'userNotFound': 'User Not Found, or is Deleted !',
  'userDeletedSuccessfully': 'User Deleted Successfully !',
  'userNotFoundOrDeactivated': 'User Not Found, or is Deactivated !',
};
